Repository Re-Spring/Do-Rering_JAVA, pull requests merged in 2024-03, with the labels that each got.

#1 [Feature]메인 홈 동화 리스트 구현 중
  src/main/java/respring/dorering/rest/story/controller/StoryController.java
  src/main/java/respring/dorering/rest/story/dto/StoryDTO.java
  src/main/java/respring/dorering/rest/story/entity/Story.java
  src/main/java/respring/dorering/rest/story/repository/StoryRepository.java
  src/main/java/respring/dorering/rest/story/service/StoryService.java
Labels: feature

#3 [Feature] 메인 홈 동화 리스트 구현 완료
  build.gradle
  src/main/java/respring/dorering/rest/story/controller/StoryController.java
  src/main/java/respring/dorering/rest/story/entity/Story.java
  src/main/java/respring/dorering/rest/story/repository/StoryRepository.java
  src/main/java/respring/dorering/rest/story/service/StoryService.java
Labels: feature

#6 [Feature] 검색 기능을 위한 기본 베이스 구현
  src/main/java/respring/dorering/rest/search/controller/SearchController.java
  src/main/java/respring/dorering/rest/search/dto/SearchDTO.java
  src/main/java/respring/dorering/rest/search/entity/FairyTale.java
  src/main/java/respring/dorering/rest/search/repository/SearchRepository.java
  src/main/java/respring/dorering/rest/search/service/SearchService.java
Labels: feature

#8 [Feature] 동화 상세 페이지 구현 중
  src/main/java/respring/dorering/rest/search/controller/SearchController.java
  src/main/java/respring/dorering/rest/search/dto/SearchDTO.java
  src/main/java/respring/dorering/rest/search/entity/FairyTale.java
  src/main/java/respring/dorering/rest/search/repository/SearchRepository.java
  src/main/java/respring/dorering/rest/search/service/SearchService.java
  src/main/java/respring/dorering/rest/story/controller/StoryController.java
  src/main/java/respring/dorering/rest/story/entity/Story.java
  src/main/java/respring/dorering/rest/story/repository/StoryRepository.java
  src/main/java/respring/dorering/rest/story/service/StoryService.java
Labels: feature

#9 [Feature] 동화 상세 페이지 구현 중
  src/main/java/respring/dorering/rest/story/controller/StoryController.java
  src/main/java/respring/dorering/rest/story/dto/StoryDTO.java
  src/main/java/respring/dorering/rest/story/service/StoryService.java
Labels: feature

#10 [Feature] search 수정본
  src/main/java/respring/dorering/rest/search/controller/SearchController.java
  src/main/java/respring/dorering/rest/search/dto/SearchDTO.java
  src/main/java/respring/dorering/rest/search/entity/FairyTale.java
  src/main/java/respring/dorering/rest/search/repository/SearchRepository.java
  src/main/java/respring/dorering/rest/search/service/SearchService.java
Labels: feature

#11 [Feature] 상세 페이지 구현 중
  src/main/java/respring/dorering/rest/fairytale/controller/DetailController.java
  src/main/java/respring/dorering/rest/fairytale/dto/DetailDTO.java
  src/main/java/respring/dorering/rest/fairytale/entity/Detail.java
  src/main/java/respring/dorering/rest/fairytale/repository/DetailRepository.java
  src/main/java/respring/dorering/rest/fairytale/service/DetailService.java
  src/main/resources/application.yml
Labels: feature

#12 [Feature] 아이디 비밀번호 찾기 구현
  src/main/java/respring/dorering/rest/auth/controller/UserController.java
  src/main/java/respring/dorering/rest/auth/entity/User.java
  src/main/java/respring/dorering/rest/auth/repository/UserRepository.java
  src/main/java/respring/dorering/rest/auth/service/UserService.java
Labels: feature

#13 [Feature] 동화 상세페이지 구현완료
  src/main/java/respring/dorering/rest/fairytale/controller/DetailController.java
  src/main/java/respring/dorering/rest/fairytale/dto/DetailDTO.java
  src/main/java/respring/dorering/rest/fairytale/entity/Detail.java
  src/main/java/respring/dorering/rest/fairytale/repository/DetailRepository.java
  src/main/java/respring/dorering/rest/fairytale/service/DetailService.java
  src/main/java/respring/dorering/rest/story/controller/StoryController.java
  src/main/java/respring/dorering/rest/story/dto/StoryDTO.java
  src/main/java/respring/dorering/rest/story/dto/StoryDetailDTO.java
  src/main/java/respring/dorering/rest/story/entity/Story.java
  src/main/java/respring/dorering/rest/story/repository/StoryRepository.java
  src/main/java/respring/dorering/rest/story/service/StoryService.java
Labels: feature

#15 [Feature] 내 정보 수정 기능 완료
  src/main/java/respring/dorering/rest/auth/service/UserService.java
  src/main/resources/application.yml
Labels: feature

#16 Feature 검색
  src/main/java/respring/dorering/rest/fairytale/controller/DetailController.java
  src/main/java/respring/dorering/rest/fairytale/dto/DetailDTO.java
  src/main/java/respring/dorering/rest/fairytale/entity/Detail.java
  src/main/java/respring/dorering/rest/fairytale/repository/DetailRepository.java
  src/main/java/respring/dorering/rest/fairytale/service/DetailService.java
  src/main/java/respring/dorering/rest/search/controller/SearchController.java
  src/main/java/respring/dorering/rest/search/dto/SearchDTO.java
  src/main/java/respring/dorering/rest/search/entity/FairyTale.java
  src/main/java/respring/dorering/rest/search/repository/SearchRepository.java
  src/main/java/respring/dorering/rest/search/service/SearchService.java
Labels: feature

#17 [Refactoring] yml 파일 수정, sql스크립트 수정
  sql/script.sql
  src/main/resources/application.yml
Labels: documentation

#18 [Refactorying] SQL스크립트 수정하였습니다
  sql/script.sql
Labels: enhancement

#19 [Feature] 회원탈퇴 및 내 동화 보기 구현
  src/main/java/respring/dorering/rest/auth/controller/UserController.java
  src/main/java/respring/dorering/rest/auth/entity/User.java
  src/main/java/respring/dorering/rest/auth/repository/UserRepository.java
  src/main/java/respring/dorering/rest/auth/service/UserService.java
  src/main/java/respring/dorering/rest/story/controller/StoryController.java
  src/main/java/respring/dorering/rest/story/dto/StoryDTO.java
  src/main/java/respring/dorering/rest/story/dto/StoryDetailDTO.java
  src/main/java/respring/dorering/rest/story/repository/StoryRepository.java
  src/main/java/respring/dorering/rest/story/service/StoryService.java
Labels: feature

#20 [Feature] 로그인 만료-1
  src/main/java/respring/dorering/rest/auth/controller/UserController.java
  src/main/java/respring/dorering/rest/auth/jwt/TokenProvider.java
Labels: feature

#22 [Feature] 회원 탈퇴 수정 완료
  src/main/java/respring/dorering/rest/auth/entity/User.java
  src/main/java/respring/dorering/rest/auth/repository/UserRepository.java
  src/main/java/respring/dorering/rest/auth/service/UserService.java
Labels: feature

#24 [Feature] 내 동화 페이지 구현 중
  src/main/java/respring/dorering/rest/story/controller/StoryController.java
  src/main/java/respring/dorering/rest/story/service/StoryService.java
Labels: feature

#25 [Feature] 탈퇴 회원 기간 만료 후 정보 삭제
  build.gradle
  src/main/java/respring/dorering/rest/admin/config/ApiKeyConfiguration.java
  src/main/java/respring/dorering/rest/admin/controller/AdminController.java
  src/main/java/respring/dorering/rest/admin/dto/VoiceDTO.java
  src/main/java/respring/dorering/rest/admin/entity/Voice.java
  src/main/java/respring/dorering/rest/admin/repository/AdminRepository.java
  src/main/java/respring/dorering/rest/admin/service/AdminService.java
  src/main/java/respring/dorering/rest/config/BeanConfiguration.java
  src/main/resources/application.yml
Labels: feature

#26 [Feature] 내 동화 페이지 구현 중
  src/main/java/respring/dorering/rest/admin/entity/Voice.java
  src/main/java/respring/dorering/rest/story/entity/Story.java
  src/main/java/respring/dorering/rest/story/repository/StoryRepository.java
  src/main/java/respring/dorering/rest/story/service/StoryService.java
Labels: feature

#27 [Feature 고객센터 백엔드]
  build.gradle
  src/main/java/respring/dorering/rest/CustomerService/controller/CustomerServicePostController.java
  src/main/java/respring/dorering/rest/CustomerService/dto/CustomerServicePostDto.java
  src/main/java/respring/dorering/rest/CustomerService/entity/CustomerServicePost.java
  src/main/java/respring/dorering/rest/CustomerService/repository/CustomerServicePostRepository.java
  src/main/java/respring/dorering/rest/CustomerService/service/CustomerServicePostService.java
Labels: feature

#28 [Feature] dockerfile add
  Dockerfile
Labels: feature

#29 [Feature] 내 동화 페이지 구현 완료
  src/main/java/respring/dorering/rest/story/controller/StoryController.java
  src/main/java/respring/dorering/rest/story/entity/Story.java
  src/main/java/respring/dorering/rest/story/repository/StoryRepository.java
  src/main/java/respring/dorering/rest/story/service/StoryService.java
Labels: feature

#31 [Feature] 메인 동화 리스트 나누기
  src/main/java/respring/dorering/rest/story/controller/StoryController.java
  src/main/java/respring/dorering/rest/story/entity/Story.java
  src/main/java/respring/dorering/rest/story/repository/StoryRepository.java
  src/main/java/respring/dorering/rest/story/service/StoryService.java
Labels: feature

#32 [Feature] 배포를위한 빌드작업
  Dockerfile
  build.gradle
  gradlew
Labels: feature

#37 [Feature] 상세페이지 동화 추가
  src/main/java/respring/dorering/rest/story/controller/StoryController.java
  src/main/java/respring/dorering/rest/story/dto/StoryDTO.java
  src/main/java/respring/dorering/rest/story/dto/StoryDetailDTO.java
  src/main/java/respring/dorering/rest/story/entity/FairytaleVideoInfo.java
  src/main/java/respring/dorering/rest/story/entity/Story.java
  src/main/java/respring/dorering/rest/story/repository/StoryRepository.java
  src/main/java/respring/dorering/rest/story/repository/VideoRepository.java
  src/main/java/respring/dorering/rest/story/service/StoryService.java
Labels: feature

#38 [Refactoring] log.info 제거
  src/main/java/respring/dorering/rest/admin/controller/AdminController.java
  src/main/java/respring/dorering/rest/admin/service/AdminService.java
  src/main/java/respring/dorering/rest/auth/controller/UserController.java
  src/main/java/respring/dorering/rest/auth/jwt/TokenProvider.java
  src/main/java/respring/dorering/rest/auth/service/UserService.java
  src/main/java/respring/dorering/rest/search/controller/SearchController.java
  src/main/java/respring/dorering/rest/search/service/SearchService.java
Labels: refectoring
